<?php

namespace Blage\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskListRepository extends EntityRepository
{
    public function findByUsername($username)
    {
        $dql = 'SELECT t FROM BlageTaskBundle:TaskList t JOIN t.user u WHERE u.username = :name';
        $query = $this->_em->createQuery($dql);
        $query->setParameter('name', $username);
        
        return $query->getResult();
    }
    
    public function findOneByUsernameAndTitle($username, $title)
    {
        $dql = 'SELECT t FROM BlageTaskBundle:TaskList t JOIN t.user u WHERE u.username = :name AND t.listTitle = :title';
        $query = $this->_em->createQuery($dql);
        $query->setParameter('name', $username);
        $query->setParameter('title', $title);
        
        return $query->getSingleResult();
    }
}