<?php

namespace Blage\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Blage\TaskBundle\Entity\User;
/**
 * ToshiInvitationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToshiInvitationsRepository extends EntityRepository
{
    public function getPendingInvitations(User $user)
    {
        $ids = array();
        $allreadyRegistered = '';
        $rsm = new \Doctrine\ORM\Query\ResultSetMapping();
        $rsm->addScalarResult('toshies_id', 'id');
        $paramQuery = $this->_em->createNativeQuery("SELECT toshies_id FROM toshi_list WHERE user_id = :userId", $rsm)->setParameter('userId', $user->getId());
        $params = $paramQuery->getResult();
        foreach($params as $id){
            $ids[] = $id['id'];
        }
        
        if(count($ids) > 0){
            $allreadyRegistered = "OR i.toshi NOT IN ( :ids )";
        }
        $dql = "SELECT i FROM BlageTaskBundle:ToshiInvitation i WHERE i.user = :userId AND (i.toshi IS NULL ".$allreadyRegistered.")";
        $query = $this->_em->createQuery($dql)->setParameter('userId', $user->getId());
        if($allreadyRegistered){
            $query->setParameter('ids', $ids);
        }
        $pendingInvitations = $query->getResult();
        
        return $pendingInvitations;
    }
}