<?php

namespace Blage\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ToshiListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToshiListRepository extends EntityRepository
{
}